// <auto-generated />
using BookStoreApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreApi.Migrations
{
    [DbContext(typeof(BookStoreApiContext))]
    partial class BookStoreApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStoreAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John",
                            Price = 500.0,
                            Stock = 10,
                            Title = "C# Basics"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Smith",
                            Price = 700.0,
                            Stock = 5,
                            Title = "ASP.NET Guide"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Robert Martin",
                            Price = 1200.0,
                            Stock = 8,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Andrew Hunt",
                            Price = 1500.0,
                            Stock = 6,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Erich Gamma",
                            Price = 1800.0,
                            Stock = 4,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Thomas H. Cormen",
                            Price = 2000.0,
                            Stock = 3,
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Andrew Stellman",
                            Price = 900.0,
                            Stock = 7,
                            Title = "Head First C#"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
